name: Status Report

on:
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:

jobs:
  report:
    name: Create issue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/status-report-template.md
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
      - uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: proj-conda-ecosystem-sta-internal
          SLACK_COLOR: "#7868E6"
          SLACK_MESSAGE: "Time to fill the weekly update :pencil: <${{ steps.create-issue.outputs.url }}>"
          SLACK_USERNAME: "GH-bot"
          SLACK_ICON_EMOJI: ":github-1:"
          MSG_MINIMAL: true
